version: '3'

services:
  url-shortener-api:
    image: bitnami/postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=url-shortener-api